### ISSUE TITLE
default color should be "currentColor"

### ISSUE THREAD

**Issue by MRezaSafari** [techwithmanuel/untitledui-js#17]
https://github.com/techwithmanuel/untitledui-js/blob/c12c67d28dff438c3247d04a19f931046777c04b/src/template.tsx#L38

both fill and stroke should be set to "currentColor" so it inherit it's color from the parent.

**Comment by techwithmanuel** [comment]
Hey @MRezaSafari for pointing this out, the update will be made along with others in the next version of the package

**Comment by techwithmanuel** [comment]
@MRezaSafari, the stroke has been adjusted to the "currentColor" in the latest update, but the fill would continue to remain "none" because it makes the icons more flexible and easier to customize using CSS
