### ISSUE TITLE
VolumeX icon

### ISSUE THREAD

**Issue by eb-73** [techwithmanuel/untitledui-js#18]
`VolumeX` icon is the same as `VolumePlus`.

**Comment by techwithmanuel** [comment]
Thank you @eb-73 for pointing this out, an update would be made in the next 48 hours

**Comment by techwithmanuel** [comment]
The issue has be resolved, update your package and you'll have access to the Volume X icon, also stay stay updated as the docs would be redesigned soon, thank you once again @eb-73  for raising this issue
