### ISSUE TITLE
Category import not supported anymore?

### ISSUE THREAD

**Issue by homayounfh** [techwithmanuel/untitledui-js#20]
until now I was using untitledui-js library importing categories which i found very convenient.
with the new version 2.1.16 my app crushes because I am just allowed to have individual imports which is cumbersome and now even when I want to go back to previous version idk why I receive error on individual imports instead that I didn't use to have before. 
is it going to be fixed or this is going to be the new approach?

**Comment by techwithmanuel** [comment]
I understand your understand your concerns. A minor update was released recently to better support tree shaking and code splitting. As a result, category-based imports had to be deprecated. The new approach of importing only the icons you need aligns with the practices of the most popular libraries, making your app more efficient and performant. The new version is 2.1.161. I apologise for any inconvenience this breaking change may have caused, but moving forward, this will be the standard.
