### ISSUE TITLE
Import individual icon

### ISSUE THREAD

**Issue by renatomserra** [techwithmanuel/untitledui-js#22]
Hello,

Is there a way to import an individual icon?
Seems with named imports it imports all of them into the bundle but then only renders the selected.
I've tried getting them via /dist/icon/IconName but i think at build time they cant be found.

**Comment by techwithmanuel** [comment]
@renatomserra which version of the library do you currently have installed

**Comment by renatomserra** [comment]
Im on 2.1.4

**Comment by techwithmanuel** [comment]
@renatomserra thank you for pointing this out, "sideEffects: false" flag has been added to the package.json to further support tree shaking in a variety of bundlers and all icons are now dynamically imported. update to the latest version v2.1.6 to see the changes. This change would be coming to the base version of the library in about 24 - 48hrs.

**Comment by renatomserra** [comment]
thank you so much!

**Comment by techwithmanuel** [comment]
🫡
