### ISSUE TITLE
"Error: Cannot find module './undefined.js'"

### ISSUE THREAD

**Issue by pradelkai** [techwithmanuel/untitledui-js#23]
Howdy,
Love this project but ran into an issue where it won't run under Next js 14.3.2 using the App Router on a client component. 
With either the base or framer motion version I get this error:
"Error: Cannot find module './undefined.js'"

Thanks,
Kai

**Comment by techwithmanuel** [comment]
@pradelkai thank you for pointing this out, this issue would be resolved soon

**Comment by techwithmanuel** [comment]
@pradelkai I am unable to replicate this issue, update your framer motion to the latest version  as of now that would be "^11.2.10" then restart your server if the issue still persists, share your repository and I'll have a look

**Comment by techwithmanuel** [comment]
A new update has been sent out addressing a variety of issues, please update your version of the library and try again.
