### ISSUE TITLE
Is it possible to import UntitledUI types?

### ISSUE THREAD

**Issue by gohanko** [techwithmanuel/untitledui-js#24]
Hi Emmanuel,

So I have been using your library to render UntitledUI icons for my project. Thank you for the great work. It has made my life a lot easier. 

I'm building my projects using Typescript, but, I've run into some issues related to that.

- Particularly, for importing types. Is it possible to import UntitledUI types into my projects? I'm trying to import `SVGComponentProps` and I've tried `import type { SVGComponentProps } from 'untitledui-js-base'` but can't seem to import them properly.
- I've also noticed that there's a difference in versions between the two packages. Is there any significant difference between `untitledui-js-base` v1.0.15 and `untitledui-js` v2.1.61?

Please reply as you wish (or not at all), no rush. Again, thank you for your work on this.

Thanks,
Brandon

**Comment by techwithmanuel** [comment]
Hey @gohanko, I'll check out the issue and get back to you soon. The base version is newer and was released after the animated version. Aside from lacking framer motion support on the base version `untitledui-js-base`, the two libraries are identical.

**Comment by techwithmanuel** [comment]
@gohanko I was unable to replicate this issue, in a variety of environments, importing types with untitledui-js and untitledui-js-base should be a straight forward process, could you share a repository where this issue exists ?
```ts
import { X, Activity } from "untitledui-js";
import { SVGComponentProps } from "untitledui-js";

const icons: React.FC<SVGComponentProps>[] = [X, Activity];

function App() {
  return (
    <div className="w-full min-h-[100vh] flex justify-center items-center">
      {icons.map((icon, index) => {
        const Icon = icon;
        return <Icon key={index} />;
      })}
    </div>
  );
}

export default App;

```

**Comment by chethanbhat** [comment]
Getting this error

![image](https://github.com/techwithmanuel/untitledui-js/assets/14086840/42aa3070-2277-465e-9dc8-1013115bb00d)

**Comment by techwithmanuel** [comment]
Is this a webpack project and if so, are you using a ts loader ??

**Comment by chethanbhat** [comment]
No I'm not using a TS Loader. This is a CRA project but updated to `"react-scripts": "^5.0.1"` and ` "react": "^18.2.0",` , so there is a no webpack config.

**Comment by techwithmanuel** [comment]
Alright I take a look into the issue and get back to you with a solution soon

**Comment by techwithmanuel** [comment]
Hey @gohanko, a new type has been released in the currently released versions of both libraries `SVGComponent`, you can now import it and type your icons 
```ts
import { Archive, Activity, SVGComponent } from "untitledui-js-base";

function App() {
  const icons: SVGComponent[] = [Archive, Activity];

  ....
}

export default App;

```
This type is also available in the main version of the library

**Comment by techwithmanuel** [comment]
Hey @chethanbhat, update the library and see if you still encounter such issue, if so reopen the issue

**Comment by gohanko** [comment]
@techwithmanuel Thanks for the new update. I apologize for not replying after creating the thread. What's the issue actually? How come you can import it, but then have to fix it? I assume that maybe it's related to CRA?
