### ISSUE TITLE
Many of the Time section icons are spelled with "Calender" instead of "Calendar"

### ISSUE THREAD

**Issue by seigler** [techwithmanuel/untitledui-js#25]
There is a typo in the naming for many Calendar items. They are misspelled "Calender".

**Comment by techwithmanuel** [comment]
Alright this would be corrected in the next version release of the library.

**Comment by techwithmanuel** [comment]
Hey @seigler thank you for pointing this out, currently icons with the misspelled icon name have been renamed in the main library in the "2.2.0" version update, this change would be coming to the base version of the library shortly
