### ISSUE TITLE
TypeError: Failed to fetch dynamically imported module: https://decide.jupi.co/assets/icons/ArrowNarrowLeft

### ISSUE THREAD

**Issue by anneclairelh** [techwithmanuel/untitledui-js#26]
Following https://github.com/techwithmanuel/untitledui-js/issues/21, I have implemented Lazy icons  using version 2.1.61 of the package.
Everything works well locally but when I deploy, the page load fails with the following error: `TypeError: Failed to fetch dynamically imported module: https://decide.jupi.co/assets/icons/ArrowNarrowLeft`. 
As a reminder I have a Vite+ReactJS app.
Do you know where the issue could come from ?
Thanks a lot!

**Comment by anneclairelh** [comment]
FYI, I am able to reproduce locally when I build and serve `dist` contents.

**Comment by techwithmanuel** [comment]
Alright I'll take a look into the issue

**Comment by techwithmanuel** [comment]
Hey @anneclairelh, please update your version of the library to the latest and if the issue persists, consider reopening the issue
