### ISSUE TITLE
Icons flicker on render due to DefaultLazyImportFallback

### ISSUE THREAD

**Issue by jacknevitt** [techwithmanuel/untitledui-js#27]
The imported icons display a dark box and cause layout shifting when rendering. Tested with both `untitledui-js` and `untitled-ui-base`.
When adding different styles to the icon, to change the size or position, these styles are not applied to the fallback element `DefaultLazyImportFallback`, causing the element to update when it's loaded in.

I suspect this could be fixed by applying the icon styles to the fallback element, but the dark box will still show.

**Comment by Scrowszinho** [comment]
I get the same issue in my projects, but when I rollback the untitled-ui-base to version 1.0.11, it works normally. I hope they fix this, I love this pack.

**Comment by alexbot89** [comment]
Having the same issue, the icons are flickering due to the fallback svg being always rendered even on subsequent re-renders, I see two areas that are probably causing this.

https://github.com/techwithmanuel/untitledui-js/blob/eb7d6862e92d1427ecd0e57eefc48594fcf16cee/src/index.tsx#L13
https://github.com/techwithmanuel/untitledui-js/blob/eb7d6862e92d1427ecd0e57eefc48594fcf16cee/src/template.tsx#L74

**Comment by brayanduranvelasquez** [comment]
> I get the same issue in my projects, but when I rollback the untitled-ui-base to version 1.0.11, it works normally. I hope they fix this, I love this pack.

Thanks for this. It works for me this way so far.

**Comment by techwithmanuel** [comment]
Hey, currently working on a new version of both libraries that would resolve a couple of rendering and compatibility issues, this version is currently still in the testing phase and would be rolling out soon

**Comment by zirho** [comment]
FYI, this seems to happen even when you resize the browser window.

**Comment by techwithmanuel** [comment]
Hello everyone, an update has been sent out to resolve this issue on both libraries, please update your version of the library to the latest in your dependencies
