### ISSUE TITLE
Icon flicker on 1.0.11+ versions

### ISSUE THREAD

**Issue by Scrowszinho** [techwithmanuel/untitledui-js#28]
Hi guys, I'm encountering a bug when using the package on versions 1.0.11 and above. When I render another component or try to load something, the icon flickers and fills with a gray color. I think the error occurs in the DefaultLazyImportFallback.

**Comment by techwithmanuel** [comment]
Hey @Scrowszinho , currently working on a new version of both libraries that would resolve a couple of rendering and compatibility issues, this version is currently still in the testing phase and would be rolling out soon

**Comment by Scrowszinho** [comment]
What a great notice. Thanks for your time and work sir. 🤩

**Comment by meltaki** [comment]
Hey! @techwithmanuel First, thank you for the awesome work. We've been using untitledui-js for our app, and our Figma/React workflow has been great. We really appreciate the effort you've put into this project.

We've also been experiencing the icon flickering issue, where icons rerender on page load and whenever anything is clicked, often flickering with a gray color. I understand you're already working on a fix, and I wanted to add that we're also encountering this problem. Thanks again for your hard work and dedication—keep it up!

**Comment by techwithmanuel** [comment]
Goodday everyone, both versions of the library have been updated to resolve the flicker issue, please update the version of the library in your dependencies.

**Comment by meltaki** [comment]
Thank you very much! It worked perfectly, and we appreciate you being on top of this @techwithmanuel.

**Comment by Scrowszinho** [comment]
Thanksk @techwithmanuel for the excellent job sir. Worked very well.
