### ISSUE TITLE
Next js build error

### ISSUE THREAD

**Issue by pedrogscruz** [techwithmanuel/untitledui-js#30]
I'm running on `next@14.2.3` and `untitledui-js@2.2.0`

<img width="670" alt="Captura de Tela 2024-08-02 às 15 44 00" src="https://github.com/user-attachments/assets/cb7ce99f-e018-406e-bae8-a440f44f7c18">

**Comment by Cutaiar** [comment]
> I'm running on `next@14.2.3` and `untitledui-js@2.2.0`
> 
> <img alt="Captura de Tela 2024-08-02 às 15 44 00" width="670" src="https://private-user-images.githubusercontent.com/31415439/354693828-cb7ce99f-e018-406e-bae8-a440f44f7c18.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2NjMyNDIsIm5iZiI6MTcyMzY2Mjk0MiwicGF0aCI6Ii8zMTQxNTQzOS8zNTQ2OTM4MjgtY2I3Y2U5OWYtZTAxOC00MDZlLWJhZTgtYTQ0MGY0NGY3YzE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE0VDE5MTU0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2MWNiYTMxNDk4NWQ0MmFiMWVjOWIwYjcwODRiNDllYWZiNzM1MjhkMDM0MmRhNzc2YzY2MDc2Njk2ZjdlNGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KV2_pSRelpdgHEooGHW0hFGp1kVU41oml0RCS21R8LE">

Having the same issue with the same versions.

**Comment by techwithmanuel** [comment]
I'll look into the issue and get back to you, you can also provide more information on any error messages you encountered while trying to build.

**Comment by techwithmanuel** [comment]
@Cutaiar  & @pedrogscruz  thank you for pointing out these issues, the underlying problem was that Next JS was unable to process the type files, but this has been resolved in the latest update "2.2.11"
